name: Process
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *" # Every day at 12AM
jobs:
  process:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3        
      - uses: asdf-vm/actions/install@v1
      - run: npm ci
      - run: ./process.sh
        env:
          SMTP_GMAIL: ${{ secrets.SMTP_GMAIL }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "data/*.sqlite"
          commit_message: Update database after processing
