name: Process
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *" # Every day at 12AM
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3        
      - uses: asdf-vm/actions/install@v1
      - run: npm ci
      - run: ./src/scripts/process.ts
        env:
          SMTP_GMAIL: ${{ secrets.SMTP_GMAIL }}
      - uses: EndBug/add-and-commit@v9
        with:
          add: "data/*.sqlite"
          message: Update database after processing
